adminproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("x_admin.urls", namespace="user"))
]

x_admin/urls.py
from django.conf.urls import url

from x_admin import views
from x_admin.views import *

app_name = "x_admin"

urlpatterns = [
    # url(r'register', Register.as_view(), name="register"),
    url(r'login', Login.as_view(), name="login"),
    url(r'viplist', Viplist.as_view(), name="viplist"),
    url(r'vipedit', Vipedit.as_view(), name="vipedit"),
    url(r'vipdel', Vipdel.as_view(), name="Vipdel"),
    url(r'adminlist', Adminlist.as_view(), name="adminlist"),
    url(r'adminadd', Adminadd.as_view(), name="adminadd"),
    url(r'adminedit', Adminedit.as_view(), name="adminedit"),
    url(r'admindel', Admindel.as_view(), name="admindel"),
    url(r'logout', Logout.as_view(), name="logout"),
    url(r'', Index.as_view(), name="index")
]
handler404=views.page_not_found

x_admin/models.py
# !/usr/bin/python
# coding=utf-8
from datetime import datetime
# Create your models here.
from django.db import models

#会员等级
class Vipadmin(models.Model):
    vipname = models.CharField(max_length=20,verbose_name='等级名称')

#用户表
class UserAdmin(models.Model):
    '''会员等级'''
    admin_super = (
        (0,'普通用户'),
        (1, '超级管理员'),
    )
    name = models.CharField(max_length=20, verbose_name='用户名',unique=True)
    password = models.CharField(max_length=120, verbose_name='密码')
    phone = models.CharField(max_length=16, verbose_name='联系电话')
    email = models.CharField(max_length=60,verbose_name='邮箱')
    is_superuser = models.SmallIntegerField(choices=admin_super,default=0,verbose_name='是否是超级管理员')
    create_time = models.DateField(max_length=50, verbose_name='创建时间')
    start = models.BooleanField(default=1, verbose_name='状态')
    vipadmin = models.ForeignKey('Vipadmin',verbose_name='关联等级',on_delete=models.CASCADE)

x_admin/views.py
# !/usr/bin/python
# coding=utf-8
import re
from django.contrib.auth.hashers import check_password, make_password
from django.contrib.messages.storage import session
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.views.generic import View
from x_admin.models import UserAdmin, Vipadmin
from django.views.decorators.csrf import csrf_exempt
from x_admin.funtion import get_hash
from django.contrib.auth import authenticate
@csrf_exempt
def page_not_found(request):
    return render(request,'404.html')

class Index(View):
    """"""
    def get(self,request):
       return render(request,'index.html')

class Viplist(View):
    def get(self,request):
        vipadmin = Vipadmin.objects.all()
        return render(request,"viplist.html",locals())
#编辑
class Vipedit(View):
    def get(self,request):
        edit_id = request.GET.get('id')
        eid = Vipadmin.objects.get(id=edit_id)
        return render(request,'vipedit.html',locals())
    def post(self, request):
        edit_id = request.POST.get('id')
        edit_name = request.POST.get('vipname')
        #添加数据
        editname=Vipadmin.objects.create(id=edit_id,vipname=edit_name)
        #更新数据信息
        # editvip = Vipadmin.objects.filter(id=edit_id).update(id=edit_id,vipname=edit_name)
        return redirect(reverse('user:viplist'),locals())

#删除
class Vipdel(View):
    def get(self,request):
        edit_id = request.GET.get('id') #herf 动态传参，获取到值
        Vipadmin.objects.filter(id=edit_id).delete()
        return redirect(reverse('user:viplist'))



class Adminlist(View):
    def get(self,request):
         adminlist= UserAdmin.objects.all()
         return render(request,"adminlist.html",locals())


#添加管理员
class Adminadd(View):
    def get(self,request):
        return render(request,'adminadd.html')
    def post(self,request):
        name = request.POST.get('name')
        email= request.POST.get('email')
        phone = request.POST.get('phone')
        is_superuser = request.POST.get('is_superuser')
        user = UserAdmin.objects.create(name=name,email=email,phone=phone,is_superuser=is_superuser)
        return redirect(reverse('user:adminlist'), locals())
#编辑管理员
class Adminedit(View):
    def get(self,request):
        edit_id = request.GET.get('id')  #获取到id
        edit = UserAdmin.objects.get(id=edit_id)
        return render(request,'adminedit.html',locals())
    def post(self,request):
        edit_id = request.GET.get('id')#获取到get提交的id,根据id进行编辑，更新。
        name = request.POST.get('name')
        email= request.POST.get('email')
        phone = request.POST.get('phone')
        is_superuser = request.POST.get('is_superuser')
        create_time = request.POST.get('create_time')
        editadmin = UserAdmin.objects.filter(id=edit_id).update(id=edit_id,name=name,email=email,phone=phone,is_superuser=is_superuser,create_time=create_time)
        return redirect(reverse('user:adminlist'), locals())


class Admindel(View):
    def get(self,request):
        admin_id = request.GET.get('id')
        useradmin = UserAdmin.objects.get(id=admin_id).delete()
        return redirect(reverse('user:adminlist'), locals())



class Login(View):
    def get(self,request):
        return render(request,"login.html")

    def post(self, request):
        '''进行登录校验'''
        # 接受数据
        name = request.POST.get('name')
        password = request.POST.get('password')
        # a=get_hash(password)
        # print a
        if not all([name,password]):
            return render(request,'login.html',{'errmsg':'用户名或密码不能为空'})
        try:
            user = UserAdmin.objects.get(name=name)
        except UserAdmin.DoesNotExist:
            user = None
        if user:
            if get_hash(password)==user.password:
                return render(request, 'index.html', locals())
            else:
                return render(request, 'login.html', {'errmsg': '用户名或密码不正确'})
        else:
            return render(request, 'login.html', {'errmsg': '用户名或密码不正确'})



class Logout(View):
    """注销"""
    def get(self, request):
        request.session.clear()
        return redirect(reverse("user:login"))

templates/adminadd.html
{% extends 'base.html' %}
{% block content %}

 <form method="post">
     {% csrf_token %}
    <div class="card">
        <div class="card-header">
            <div class="card-title">添加</div>
        </div>
        <div class="card-body">
            <div class="form-group">
                <input type="text" class="form-control" name="name"  placeholder="用户名">
            </div>

            <div class="form-group">
                <input type="text" class="form-control " name="email"   placeholder="邮箱">
            </div>
            <div class="form-group">
                <input type="text" class="form-control " name="phone"  placeholder="电话">
            </div>

            <div class="form-group">
                <input type="text" class="form-control "  value="{{ add.is_superuser }}"  placeholder="等级">
            </div>
{#            <div class="form-group">#}
{#                 <span class="text-danger">*时间格式：XXXX-XX-XX</span>#}
{#                <input type="text" class="form-control " name="create_time"  placeholder="创建时间">#}
{#            </div>#}

            <div class="card-action">
                <button class="btn btn-success" type="submit">增加</button>
            </div>
        </div>

    </div>
    </form>






{% endblock %}

templates/adminedit.html
{% extends 'base.html' %}
{% block content %}

 <form method="post">
     {% csrf_token %}
    <div class="card">
        <div class="card-header">
            <div class="card-title">编辑</div>
        </div>
        <div class="card-body">
            <div class="form-group">
                <input type="text" class="form-control" name="name" value="{{ edit.name }}"  placeholder="用户名">
            </div>

            <div class="form-group">
                <input type="text" class="form-control " name="email" value="{{ edit.email }}"  placeholder="邮箱">
            </div>
            <div class="form-group">
                <input type="text" class="form-control " name="phone" value="{{ edit.phone }}"  placeholder="电话">
            </div>

            <div class="form-group">
                <input type="text" class="form-control " name="is_superuser" value="{{ edit.is_superuser }}"  placeholder="等级">
            </div>
            <div class="form-group">
                 <span class="text-danger">*时间格式：XXXX-XX-XX</span>
                <input type="text" class="form-control " name="create_time" value="{{ edit.create_time }}"  placeholder="创建时间">
            </div>

            <div class="card-action">
                <button class="btn btn-success" type="submit">编辑</button>
            </div>
        </div>

    </div>
    </form>
{% endblock %}

templates/adminlist.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <link rel="stylesheet" href="{% static "assets/css/bootstrap.min.css" %}">
    <script src="{% static "assets/js/core/jquery.3.2.1.min.js" %}"></script>

    <div class="card">
        <div class="card-header ">
            <h4 class="card-title">管理员</h4>
            <p class="card-category">管理员列表</p>
               <div class="td-actions text-right" >
                   <div class="col-lg-4 col-md-9 col-sm-12"  style="width: 100px">
                       <button id="displayNotif" class="btn btn-success" ><a href="{% url 'user:adminadd' %}"><span>添加管理员</span></a></button>

                   </div>
{#                            <div class="form-button-action">#}
{#                                <button type="button" data-toggle="tooltip" title="Add"#}
{#                                        class="btn btn-link btn-simple-danger">#}
{#                                    <i class="la la-edit" style="width: 250px"><a href="{% url 'user:adminadd' %}"><span>添加管理员</span></a></i>#}
{#                                </button>#}
{#                            </div>#}
        </div>
        <div class="card-body">
            <table class="table table-head-bg-success table-striped table-hover">
                <thead>
                <tr>
                    <th scope="col">用户名</th>
                    <th scope="col">邮箱</th>
                    <th scope="col">电话</th>
                    <th scope="col">等级</th>
                    <th scope="col">创建时间</th>
                    <th scope="col" style="width:110px" >操作</th>
                </tr>
                </thead>
                <tbody>
                {% for admin in adminlist %}
                <tr>
                    <td>{{ admin.name }}</td>
                    <td>{{ admin.email }}</td>
                    <td>{{ admin.phone }}</td>
                    {% if admin.is_superuser == 0  %}
                        <td>普通用户</td>
                    {% else  %}
                         <td>超级用户</td>
                    {% endif %}
                    <td>{{ admin.create_time }}</td>
                    <td class="td-actions text-right">
                            <div class="form-button-action">
                                <button type="button" data-toggle="tooltip" title="Edit"
                                        class="btn btn-link btn-simple-danger">
                                    <i class="la la-edit"><a href="{% url 'user:adminedit' %}?id={{ admin.id }}"><span>编辑</span></a></i>
                                </button>

                                <button type="button" data-toggle="tooltip" title="Remove"
                                        class="btn btn-link btn-simple-danger">
                                    <i class="la la-times"><a href="{% url 'user:admindel' %}?id={{ admin.id }}"><span>删除</span></a></i>
                                </button>
                            </div>
                        </td>

                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {{ current_page.object_list }}
            <nav >
          <ul class="pagination">
               {% if current_page.has_previous %}
              <li><a href="?page={{ current_page.previous_page_number  }}">上一页<span class="sr-only">(current)</span> </a></li>
                {% endif %}
{#        {% pagination current_page paginator 12 5 as page_list %}  <!-- 引用自定义标签，并传入参数 -->#}

                {{ page_list|safe }}  <!--  显示 -->

                {% if current_page.has_next %}
              <li><a href="?page={{ current_page.next_page_number }}">下一页 <span class="sr-only">(current)</span></a></li>
                {% endif %}
          </ul>
            </nav>
        </div>
    </div>
    <script>
    $(document).ready(function(){
        $('.pagination li a').each(function(){

           if ( $(this).html() == {{ current_page.number }} ){
               $(this).parent().addClass('active')
           }
        });

    })


</script>

{% endblock %}

templates/login.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>登录</title>
    <link rel="stylesheet" href="{% static "assets/css/bootstrap.min.css" %}">
</head>
<body>
<div style="width: 800px;margin: 0 auto;">
    <form method="post">
          {% csrf_token %}
    <div class="card">
        <div class="card-header">
            <div class="card-title">登录</div>
        </div>
        <div class="card-body">
            <div class="form-group">
                <label for="squareInput">用户名</label>
                <input type="text" class="form-control input-square" name="name" id="squareInput" placeholder="">
            </div>
{#            <div class="col-xs-4">#}
{#                {% if errmsg %}#}
{#                    <span class="errors">{{ errmsg }}</span>#}
{#                {% else %}#}
{#                    <span>* 格式不匹配</span>#}
{#                {% endif %}#}
{#                </div>#}
            <div class="form-group">
                <div class="col-xs-4">
                    {% if errors %}
                        <span class="error_tip">{{ errmsg }}</span>
                    {% else %}
                        <span>* 至少8位密码</span>
                    {% endif %}
                </div>
                <label for="squareInput">密码</label>
                <input type="password" class="form-control input-square" name="password" id="squareInput" placeholder="">

            </div>

            <div class="card-action">
                <button class="btn btn-success" type="submit">登录</button>
                 <div class="col-xs-4">
                    {% if errors %}
                        <span class="error_tip">{{ errmsg }}</span>
                    {% else %}
                        <span></span>
                    {% endif %}
                </div>
{#                 <a href="{% url 'user:register' %}" class="btn btn-link">未注册用户, 先注册</a>#}
            </div>
        </div>
    </div>
    </form>
</div>

</body>
</html>

templates/register.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>注册</title>
    <link rel="stylesheet" href="{% static "assets/css/bootstrap.min.css" %}"/>
</head>
<body>
{#/*action="{% url 'user:login' %}" */#}
 <form method="post" >
<div style="width: 800px;margin: 0 auto;">
      {% csrf_token %}
    <div class="card">
        <div class="card-header">
            <div class="card-title">注册</div>
        </div>
        <div class="card-body">
            <div class="form-group">
                <label for="squareInput">邮箱</label>
                <input type="text" class="form-control input-square" name="email" id="squareInput" placeholder="">
            </div>
            <div class="form-group">
                <label for="squareInput">用户名</label>
                <input type="text" class="form-control input-square" name="name" id="squareInput" placeholder="">
            </div>
            <div class="form-group">
                <label for="squareInput">密码</label>
                <input type="password" class="form-control input-square" name="password1" id="squareInput" placeholder="">
            </div>
             <div class="form-group">
                <label for="squareInput">确认密码</label>
                <input type="password" class="form-control input-square" name="password2" id="squareInput" placeholder="">
            </div>
            <div class="card-action">
                <button class="btn btn-success" type="submit" >注册</button>
                 <a href="{% url 'user:login' %}" class="btn btn-link">已有用户请登录</a>
            </div>
        </div>
    </div>

</div>
 </form>
</body>
</html>

templates/vipedit.html
{% extends "base.html" %}
{% block title %}会员修改{% endblock title %}
{% block content %}
    <form method="post">
     {% csrf_token %}
    <div class="card">
        <div class="card-header">
            <div class="card-title">编辑</div>
        </div>
        <div class="card-body">
            <div class="form-group">
                <input type="text" class="form-control " name="id" value="{{ eid.id }}"  placeholder="序号">
            </div>

            <div class="form-group">
                <input type="text" class="form-control " name="vipname" value="{{ eid.vipname }}"  placeholder="等级">
            </div>

            <div class="card-action">
                <button class="btn btn-success" type="submit">增加</button>
            </div>
        </div>

    </div>

    </form>


{% endblock %}

templates/viplist.html
{% extends "base.html" %}
{% block title %}会员列表{% endblock title %}

{% block content %}
    <p>会员列表</p>

    <div class="card card-tasks">
        <div class="card-header ">
            <h4 class="card-title">会员管理</h4>
            <p class="card-category">会员等级列表</p>
        </div>
        <div class="card-body ">
            <div class="table-full-width">
                <table class="table">
                    <thead>
                    <tr>
                        <th>
                            <div class="form-check">
                                <label class="form-check-label">
                                    <input class="form-check-input  select-all-checkbox"
                                           type="checkbox" data-select="checkbox"
                                           data-target=".task-select">
                                    <span class="form-check-sign">序号</span>
                                </label>
                            </div>
                        </th>
                        <th>等级</th>
                        <th style="width:110px">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        {% for vip in vipadmin %}
                        <td>
                            <div class="form-check">
                                <label class="form-check-label">
                                    <input class="form-check-input task-select" type="checkbox">
                                    <span class="form-check-sign">{{ vip.id }}</span>
                                </label>
                            </div>
                        </td>
                        <td>{{ vip.vipname }}</td>
                        <td class="td-actions text-right">
                            <div class="form-button-action">
                                <button type="button" data-toggle="tooltip" title="Edit Task"
                                        class="btn btn-link <btn-simple-primary">
                                    <i class="la la-edit"> <a href="{% url 'user:vipedit' %}?id={{ vip.id }}"><span>编辑</span></a></i>

                                </button>
                                <button type="button" data-toggle="tooltip" title="Remove"
                                        class="btn btn-link btn-simple-danger">
                                    <i class="la la-times"><a href="{% url 'user:Vipdel' %}?id={{ vip.id }}"><span>删除</span></a></i>
                                </button>
                            </div>
                        </td>

                    </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
{#        <div class="card-footer ">#}
{#            <div class="stats">#}
{#                <i class="now-ui-icons loader_refresh spin"></i> Updated 3 minutes ago#}
{#            </div>#}
{#        </div>#}
    </div>
{% endblock %}